# render.yaml
services:
  # Backend service
  - type: web
    name: harambee-hub-backend
    env: node
    build:
      path: ./server
      nodeVersion: "18.x"
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        fromDatabase:
          name: harambee-hub-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: CLIENT_URL
        value: https://harambee-hub-frontend.onrender.com
    plan: free

  # Frontend service
  - type: web
    name: harambee-hub-frontend
    env: node
    build:
      path: ./client
      nodeVersion: "18.x"
      buildCommand: npm install && npm run build
      staticPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://harambee-hub-backend.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    plan: free

# Database (MongoDB Atlas)
databases:
  - name: harambee-hub-db
    databaseName: harambee
    plan: free
